---
- name: Runnerのディレクトリを作成
  become: false
  ansible.builtin.file:
    path: "{{ github_runner_dir }}"
    state: directory
    mode: "0755"

- name: Dockerfileテンプレートの配置
  become: false
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ github_runner_dir }}/Dockerfile"
    mode: "0644"

- name: エントリーポイントスクリプトテンプレートの配置
  become: false
  ansible.builtin.template:
    src: entrypoint.sh.j2
    dest: "{{ github_runner_dir }}/entrypoint.sh"
    mode: "0755"

- name: Docker Composeテンプレートの配置
  become: false
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ github_runner_dir }}/docker-compose.yml"
    mode: "0644"

- name: ランナーコンテナのビルドおよび起動
  become: false
  community.docker.docker_compose_v2:
    project_src: "{{ github_runner_dir }}"
    state: present
    build: always