services:
  db:
    image: postgres:15-alpine
    container_name: shake_postgres
    restart: always
    user: "${PG_UID}:${PG_GID}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PKDB_READER_USER: ${PKDB_READER_USER}
      PKDB_READER_PASSWORD: ${PKDB_READER_PASSWORD}
      PKDB_EDITOR_USER: ${PKDB_EDITOR_USER}
      PKDB_EDITOR_PASSWORD: ${PKDB_EDITOR_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: shake_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db-backup:
    image: eeshugerman/postgres-backup-s3:15
    container_name: shake_postgres-backup
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "@daily"
      S3_ENDPOINT: "https://${CF_ACCOUNT_ID}.r2.cloudflarestorage.com"
      S3_REGION: "auto"
      S3_ACCESS_KEY_ID: ${CF_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${CF_SECRET_KEY}
      S3_BUCKET: ${CF_BUCKET_NAME}
      S3_PREFIX: "db-backups"
