FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    git \
    sudo \
    ansible \
    jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m runner && \
    echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER runner
WORKDIR /home/runner

ARG RUNNER_VERSION="{{ github_runner_version }}"
ARG RUNNER_ARCH="{{ github_runner_arch }}"
RUN mkdir actions-runner && cd actions-runner && \
    curl -o actions-runner-linux.tar.gz -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz && \
    tar xzf ./actions-runner-linux.tar.gz && \
    rm -f actions-runner-linux.tar.gz

WORKDIR /home/runner/actions-runner

COPY --chown=runner:runner entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
