#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${PKDB_READER_USER} WITH PASSWORD '${PKDB_READER_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${PKDB_READER_USER};
    GRANT USAGE ON SCHEMA public TO ${PKDB_READER_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${PKDB_READER_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${PKDB_READER_USER};

    CREATE USER ${PKDB_EDITOR_USER} WITH PASSWORD '${PKDB_EDITOR_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${PKDB_EDITOR_USER};
    GRANT USAGE ON SCHEMA public TO ${PKDB_EDITOR_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${PKDB_EDITOR_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PKDB_EDITOR_USER};
EOSQL
