#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${SHAKEWEB_DB};

    CREATE USER ${SHAKEWEB_READER_USER} WITH PASSWORD '${SHAKEWEB_READER_PASSWORD}';
    CREATE USER ${SHAKEWEB_EDITOR_USER} WITH PASSWORD '${SHAKEWEB_EDITOR_PASSWORD}';

    GRANT CONNECT ON DATABASE ${SHAKEWEB_DB} TO ${SHAKEWEB_READER_USER};
    GRANT CONNECT ON DATABASE ${SHAKEWEB_DB} TO ${SHAKEWEB_EDITOR_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SHAKEWEB_DB" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO ${SHAKEWEB_READER_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${SHAKEWEB_READER_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${SHAKEWEB_READER_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${SHAKEWEB_READER_USER};

    GRANT USAGE, CREATE ON SCHEMA public TO ${SHAKEWEB_EDITOR_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${SHAKEWEB_EDITOR_USER};
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${SHAKEWEB_EDITOR_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SHAKEWEB_EDITOR_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${SHAKEWEB_EDITOR_USER};
EOSQL
