[proxy_node]
negitoroserver ansible_host=100.92.253.28 ansible_user=ansible_admin

[home_node1]
shakeserver ansible_host=100.116.167.59 ansible_user=ansible_admin

[home_node2]
tarakoserver ansible_host=100.123.163.119 ansible_user=ansible_admin

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
