services:
  minecraft-server:
    image: itzg/minecraft-server:java21
    container_name: shake_minecraft-pixelmon1.21.1
    restart: always
    environment:
      UID: "${MC_UID}"
      GID: "${MC_GID}"
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "NEOFORGE"
      NEOFORGE_VERSION: "LATEST"
      MEMORY: "3G"
      SERVER_NAME: "kogakumon"
      GAMEMODE: "survival"
      DIFFICULTY: "peaceful"
      ALLOW_FLIGHT: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${MC_RCON_PASSWORD}"
      RCON_PORT: 25575
      SNOOPER_ENABLED: "FALSE"
      MOTD: "§a§lPixelmon Reforged 1.21.1§b\ninfo> https://ruruthegeek.dpdns.org/mcserver/"
      OPS: "ruruthegeek,Baked_sususu"
      EXISTING_OPS_FILE: "SKIP"
      TZ: "Asia/Tokyo"
      SERVER_PORT: 25565
      SIMULATION_DISTANCE: 4
      RESOURCE_PACK: "${MC_RESOURCE_PACK_URL}"
      RESOURCE_PACK_SHA1: "${MC_RESOURCE_PACK_HASH}"
      CURSEFORGE_FILES: "https://www.curseforge.com/minecraft/mc-mods/pixelmon,https://www.curseforge.com/minecraft/mc-mods/ore-excavation"
      CF_API_KEY: "${CF_API_KEY}"
      REMOVE_OLD_MODS: "TRUE"
      RCON_CMDS_STARTUP: |-
        gamerule keepInventory true
    ports:
      - "25565:25565/tcp"
      - "127.0.0.1:25575:25575"
    volumes:
      - ./pixelmon:/data
  minecraft-backup:
    image: itzg/mc-backup
    container_name: shake_minecraft-pixelmon1.21.1-backup
    restart: always
    environment:
      RCON_HOST: "minecraft-server"
      RCON_PORT: 25575
      RCON_PASSWORD: "${MC_RCON_PASSWORD}"
      INITIAL_DELAY: "2m"
      BACKUP_INTERVAL: "24h"
      PRUNE_BACKUPS_DAYS: 7
      BACKUP_METHOD: "rclone"
      RCLONE_REMOTE: "r2"
      RCLONE_DEST_DIR: "/minecraft-backups"
      RCLONE_CONFIG_R2_TYPE: "s3"
      RCLONE_CONFIG_R2_PROVIDER: "Cloudflare"
      RCLONE_CONFIG_R2_ACCESS_KEY_ID: "${CF_ACCESS_KEY}"
      RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: "${CF_SECRET_KEY}"
      RCLONE_CONFIG_R2_ENDPOINT: "https://${CF_ACCOUNT_ID}.r2.cloudflarestorage.com"
      RCLONE_CONFIG_R2_REGION: "auto"
    volumes:
      - ./pixelmon:/data:ro
